jquery_lang_js.prototype.lang.en = {
    'Accueil':'Home',
    'Représentants':'Representatives',
    'Charte':'Charter',
    'Contact':'Contact',
    'English':'Français',
    'Bienvenue sur le site officiel de l\'AEGLO, votre association pour étudiants en Génie Logiciel. Vous trouverez ici les liens vers toutes les ressources importantes en lien avec le baccalauréat en Génie Logiciel à l\'<a href="http://www.ulaval.ca/">Université Laval</a> ainsi que les événements, sorties, partys, etc.':'Welcome to your software engineering association website. You will find here links to all the important informations about the <a hreg="http://www.ulaval.ca/">Université Laval</a> software engineering program. Also useful infomations on events, activities, parties, etc.',
    'Groupe Facebook':'Facebook Group',
    'Rejoins le groupe Facebook de l\'AEGLO pour discuter avec les membres de l\'association et des anciens élèves du programme.':'Join AEGLO Facebook group to discuss with association members and former program students.',
    ' Rejoindre le groupe »':' Join group »',
    'Liens':'Links',
    'Importants':'Importants',
    'Activités':'Activities',
    'Affaires':'Services',
    'Cours':'Classes',
    'Grilles de cheminement Génie Logiciel':'Software engineering progression chart',
    'Département d\'informatique et génie logiciel':'Computer science and software engineering departement',
    'AEGLO - Groupe Facebook':'AEGLO - Facebook Group',
    'ASETIN - Association des étudiants en informatique':'ASETIN - Computer science students association',
    'ASETIN - Groupe Facebook':'ASETIN - Facebook Group',
    'Aux initiés 2014!':'To initiates 2014!',
    ' Groupe de l\'initiation 2014 »':' Initiation 2014 Group »',
    'INITIATION 2014 - Page de l\'ASETIN':'INITIATION 2014 - ASETIN\'s Page',
    'CS Games - Compétition d\'informatique de niveau international':'CS Games - International computer science competition',
    'Festival de science et génie':'Science and Engineering festival',
    'Jeux de Génie':'Engineering Games',
    'Gaming IFT-GLO - Groupe Facebook':'Gaming IFT-GLO - Facebook Group',
    'Faculté des sciences et de génie':'Faculty of Science and Engineering',
    'Nouveaux cours de science disponibles':'New available science classes',
    'Téléphone':'Phone',
    'Courriel':'Email',
    '418-656-2131 poste 7053':'418-656-2131 extension 7053',
    'Présidente':'President',
    'Vice-présidente':'Vice-president',
    'Secrétaire-trésorier':'Secretary-treasurer',
    'Rep. aux communications':'Communications Rep.',
    'Rep. aux affaires pédagogiques':'Rep. for Pedagogical affairs',
    'Rep. aux activités socioculturelles':'Rep. for social and cultural activities',
    'Rep. aux activités finissantes':'Rep. for graduates\' activities',
    'Rep. aux affaires externes':'Rep. for extern meetings',
    'Rep. génie logiciel':'Software engineering Rep.',
    'Pour contacter tous les représentants :':'To contact all representatives at once :',
    'Café gratuit pour tous les membres de l\'association. Passe au local de l\'AEGLO et prépare-toi un café gratuit!':'Free coffee for all association\'s members. Drop by AEGLO\'s gathering room and be ready for a free coffee!',
    'Soirées LAN organisées avec boissons et barres de chocolat gratuites. Partys et soirées avec consommations payées!':'LAN party with free soft drinks and chocolate bars. Parties and happy hours with free alcoholic beverages!',
    'L\'AEGLO fournit une bibliothèque avec une grande majorité des livres demandés dans les cours d\'informatique et génie logiciel.':'AEGLO provide a library containing most of the required books for software engineering and computer science classes.',
    'Partage avec nous tes projets de développement. Fais un pull-request sur <a href="https://github.com/aeglo">GitHub</a> ou envoie un message à <a href="mailto:aeglo@aeglo.ift.ulaval.ca">aeglo@aeglo.ift.ulaval.ca</a> pour devenir collaborateur et ajouter tes projets!':'Share with us your own developpement projects. Submit a pull-request on <a href="https://github.com/aeglo">GitHub</a> or send a message to <a href="mailto:aeglo@aeglo.ift.ulaval.ca">aeglo@aeglo.ift.ulaval.ca</a> to be a contributor and add your projects!',
}
